version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: install pre-reqs
          command: |
            pip install awscli --user
            pip install aws-sam-cli --user
            mkdir functions/packed
      - run:
          name: ZIP ami_lookup Functions
          command: |
            f="ami_lookup"
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .
      - run:
          name: ZIP api_ami_get Functions
          command: |
            f="api_ami_get"
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .
      - run:
          name: ZIP cache_schedule_lookup Functions
          command: |
            f="cache_schedule_lookup"
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .
      - run:
          name: ZIP db_read Functions
          command: |
            f="db_read"
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .
      - run:
          name: ZIP db_write Functions
          command: |
            f="db_write"
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .

      - run:
          name: Sync S3 Bucket
          command: "~/.local/bin/aws s3 sync functions/packed s3://$S3_BUCKET/functions --delete"



# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
