version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install pre-reqs
          command: |
            npm install -g serverless

      - run:
          name: Deploy using Serverless
          command: |
            sls deploy -v
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
