version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: install pre-reqs
          command: |
            pip install awscli --user
            mkdir functions/packed
      - run:
          name: ZIP ami_lookup Functions
          command: |
            export COMMIT=${CIRCLE_SHA1:0:7}
            f="ami_lookup"
            f2=${$f_$COMMIT}
            echo $f2
            cd functions/$f
            pip install -r requirements.txt --target .
            zip -r9 ../packed/$f.zip .
            cp ../packed/$f.zip ../packed/$f2zip
            ls -la ../packed
      - run:
          name: Sync functions to S3 Bucket
          command: "~/.local/bin/aws s3 sync functions/packed s3://$S3_BUCKET/functions --delete"

      - run:
          name: Sync templates to S3 Bucket
          command: "~/.local/bin/aws s3 sync templates s3://$S3_BUCKET/templates --delete"

      - run:
          name: Deploy to CloudFormation
          command: |
            ~/.local/bin/aws cloudformation deploy --template-file templates/master.cfn.yml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --region $AWS_REGION --parameter-overrides TemplateBucketName=$S3_BUCKET TemplateBucketPrefix=$TemplateBucketPrefix
          no_output_timeout: 3600
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
