version: 2
jobs:
  build:
    working_directory: /
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: Pip install aws cli
          command: "pip install awscli -y"
      - run:
          name: Check/Create S3 Bucket
          command: |
            if aws s3 ls "s3://$S3_BUCKET" 2>&1 | grep -q 'AllAccessDisabled'
            then
              echo "s3://$S3_BUCKET doesn\'t exist"
              echo "Creating s3://$S3_BUCKET"
              aws s3api create-bucket --bucket $S3_BUCKET --region $AWS_REGION
              exit
            fi



# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
