version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install pre-reqs
          command: |
            sudo npm install -g serverless
            sudo npm install serverless-domain-manager
      - run:
          name: Deploy ami_lookup using Serverless
          command: |
            cd functions/ami_lookup
            sls deploy --stage dev -v
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
