# serverless.yml

service: ami_lookup_service

provider:
  name: aws
  runtime: python3.6
  stage: $(file(../../config/$(self.provider.stage).json):stage)
  region: us-east-1
  environment:
    SERVICE_NAME: ${self:service}

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: $(file(../../config/$(self.provider.stage).json):domainname) # Change this to your domain.
    basePath: 'users' # This will be prefixed to all routes
    stage: ${self:provider.stage}
    createRoute53Record: true
