AWSTemplateFormatVersion: "2010-09-09"
Description: AMI Lookup CloudFormation templates
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  env:
    Type: String
    Description: Environment Name
    Default: dev
  ArtifactsBucket:
    Type: String
    Description: Artifacts s3 bucket
    Default: dev-amilookup-artifacts
  LambdaKey:
    Type: String
    Description: Key for Lambda FunctionName
  TemplateBucketS3URL:
    Type: String
    Description: s3 URL
    Default:
  TemplateBucketName:
    Type: String
    Description: S3 Bucket Hosting Templates
  TemplateBucketPrefix:
    Type: String
    Description: S3 Templates Bucket Prefix
Resources:
  amilookupFunction:
    # This resource creates a Lambda function.
    Type: 'AWS::Serverless::Function'
    Properties:
      # This function uses the Nodejs v6.10 runtime.
      Runtime: python3.7
      # This is the Lambda function's handler.
      Handler: ami_lookup.lambda_handler
      # The location of the Lambda function code.
      CodeUri: ../functions/ami_lookup
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        ThumbnailApi:
            # Define an API Gateway endpoint that responds to HTTP GET at /thumbnail
            Type: Api
            Properties:
                Path: /ami
                Method: GET
