AWSTemplateFormatVersion: "2010-09-09"
Description: AMI Lookup CloudFormation templates
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  env:
    Type: String
    Description: Environment Name
    Default: dev
  ArtifactsBucket:
    Type: String
    Description: Artifacts s3 bucket
    Default: dev-amilookup-artifacts
  TemplateBucketS3URL:
    Type: String
    Description: s3 URL
    Default: s3.us-east-1.amazonaws.com
  TemplateBucketName:
    Type: String
    Description: S3 Bucket Hosting Templates
    Default: dev-amilookup-artifacts
  TemplateBucketPrefix:
    Type: String
    Description: S3 Templates Bucket Prefix
    Default: functions

Globals:
  Function:
    Runtime: python3.7
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'dev.amilookup.com'"

Resources:
  amilookupFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: ami_lookup.lambda_handler
      CodeUri:
        Bucket: !Ref TemplateBucketName
        Key: !Sub ${TemplateBucketPrefix}/ami_lookup.zip
      Events:
        amilookupApi:
            Type: Api
            Properties:
                Path: /ami
                Method: GET
  dbreadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: db_read.lambda_handler
      CodeUri:
        Bucket: !Ref TemplateBucketName
        Key: !Sub ${TemplateBucketPrefix}/db_read.zip
