AWSTemplateFormatVersion: "2010-09-09"
Description: AMI Lookup CloudFormation templates

Parameters:
  env:
    Type: String
    Description: Environment Name
    Default: dev
  ArtifactsBucket:
    Type: String
    Description: Artifacts s3 bucket
    Default: dev-amilookup-artifacts
  LambdaKey:
    Type: String
    Description: Key for Lambda FunctionName
  TemplateBucketS3URL:
    Type: String
    Description: s3 URL
    Default:
  TemplateBucketName:
    Type: String
    Description: S3 Bucket Hosting Templates
  TemplateBucketPrefix:
    Type: String
    Description: S3 Templates Bucket Prefix
Resources:
  amilookupStack:
   Type: AWS::CloudFormation::Stack
   Properties:
     TemplateURL: !Join [/, 'TemplateBucketS3URL', !Ref 'TemplateBucketName', templates/ami_lookup.cfn.yml]
     Parameters:
       ParentStackName: !Ref "AWS::StackName"
